/**
 * Project Gallery Component
 */
import ProjectMasonryGalleryComponent1 from "/components/masonryImageList/masonryImageListBlueBottle/masonryImageListBlueBottle.tsx";
import ProjectMasonryGalleryComponent2 from "/components/masonryImageList/masonryImageListSaenzHerrera/masonryImageListSaenzHerrera.tsx";
import ProjectMasonryGalleryComponent3 from "/components/masonryImageList/masonryImageListHabitadSinergia/masonryImageListHabitadSinergia.tsx";
import ProjectMasonryGalleryComponent4 from "/components/masonryImageList/masonryImageListArteYModa/masonryImageListArteYModa.tsx";

const Projects = [
  {
    id: "1",
    title: "Blue Bottle Coffee Shop",
    subtitle: "Commercial Design",
    slug: "project-cafeteria-bluebottle",
    pimg: "/images/project/project-cafeteria-bluebottle/architectural-visualizations/sceneSlug2.webp",
    phero:
      "/images/project/project-cafeteria-bluebottle/architectural-visualizations/sceneSlug2.webp",
    sing: "/images/project/project-cafeteria-bluebottle/sing.webp",
    num: "04",
    date: "March 2024",
    location: "Cartago, Costa Rica",
    dis: "",
    architect: "Jonnathan Brenes",
    client: "Blue Bottle",
    description:"The Blue Bottle Coffee Shop project is a masterclass in spatial optimization, redefining the urban cafe experience through a cohesive design language that balances industrial precision with organic warmth. The project was meticulously organized to generate distinct environments—service, seating, kitchen, and delivery—all living under a unified conceptual umbrella. By utilizing a consistent material palette and a strategic layout, the design achieves a seamless transition between high-activity zones like the blue-toned service counter and more serene areas such as the internal salon and the integrated outdoor terrace. \n\nEvery square meter is leveraged to enhance both operational flow and customer comfort. The interior features a striking interplay of textures, where custom blue-and-white terrazzo flooring meets the natural warmth of light timber and woven rattan accents. Organic-shaped mirrors and chevron-patterned screens create visual depth without cluttering the floor plan. This strategic zoning—incorporating a dedicated delivery window, varied seating typologies, and lush greenery—ensures the space remains highly functional for staff while offering a versatile, inviting atmosphere that encourages both quick visits and long stays.",
    elevationsSectionsDesc: "Detailed vertical views illustrate the custom architectural features, from chevron-patterned screens to the specific heights of the service counter. These drawings highlight the project's technical precision and the integration of unique design elements.",
    floorPlansDesc: "Strategic spatial planning maximizes the footprint, clearly defining the transition between the kitchen, service area, and customer seating. The layout ensures efficient operational flow while maintaining an open, inviting atmosphere for guests.",
    moodBoardDesc: "A curated selection of textures and tones defines the project's identity, featuring signature blues balanced by Aesthetic White and Felted Wool. This board anchors the design, harmonizing industrial terrazzo with organic timber and rattan elements.",
    visualizationsDesc: "High-fidelity renderings capture the intended atmosphere, showcasing the interplay of natural light with our custom blue palette. These visualizations serve as a vital bridge between conceptual theory and the final physical execution of the coffee shop.",
    builtDesc: "The completed space brings the digital vision to life, demonstrating how the conceptual zoning effectively serves daily operations. The final build confirms the success of the material selection and the seamless spatial flow designed for the brand.",
    projectGalleryDesc:"A comprehensive collection of views showcasing the cohesive brand identity across various environments. This gallery documents the design's versatility, highlighting everything from the industrial kitchen core to the serene, light-filled seating areas.",
    elevationsSections: [
      "/images/project/project-cafeteria-bluebottle/elevations-sections/sec1.webp",
      "/images/project/project-cafeteria-bluebottle/elevations-sections/sec2.webp",
      "/images/project/project-cafeteria-bluebottle/elevations-sections/sec3.webp",
    ],
    floorPlans: [
      "/images/project/project-cafeteria-bluebottle/floor-plans/fplan1.webp",
      "/images/project/project-cafeteria-bluebottle/floor-plans/fplan2.webp",
      "/images/project/project-cafeteria-bluebottle/floor-plans/fplan3.webp",
    ],
    isometricViews: [],
    moodBoard: [
      "/images/project/project-cafeteria-bluebottle/mood-board/moodboard1.webp",
      "/images/project/project-cafeteria-bluebottle/mood-board/moodboard2.webp",
      "/images/project/project-cafeteria-bluebottle/mood-board/moodboard3.webp",
    ],
    built: [
      "/images/project/project-cafeteria-bluebottle/built-project/built1.webp",
      "/images/project/project-cafeteria-bluebottle/built-project/built2.webp",
      "/images/project/project-cafeteria-bluebottle/built-project/built3.webp",
    ],
    visualizations: [
      "/images/project/project-cafeteria-bluebottle/architectural-visualizations/sceneSlug3.webp",
      "/images/project/project-cafeteria-bluebottle/architectural-visualizations/sceneSlug4.webp",
      "/images/project/project-cafeteria-bluebottle/masonry/scene13.webp",
    ],
    galleryComponent: ProjectMasonryGalleryComponent1,
  },
  {
    id: "2",
    title: "Educational Center Dr. Carlos Saenz Herrera",
    subtitle: "School Design",
    slug: "project-escuela-Dr-Saenz",
    pimg: "/images/project/project-escuela-dr-saenz/pimg.jpeg",
    phero: "/images/project/hero-project-2/img-4.jpg",
    sing: "/images/project/project-escuela-dr-saenz/sing.jpeg",
    num: "04",
    date: "December 2025",
    location: "Cartago, Costa Rica",
    dis: "",
    description: "The Educational Complex project is a pioneering architectural response that treats physical space as a responsive interface, applying UX/UI design principles to the learning environment. Grounded in the Universal Design for Learning (UDL) theory and strict adherence to Law 7600 accessibility standards, the project ensures an inclusive experience where the architecture adapts to the student, rather than the student to the building. The layout is strategically zoned to include specialized Emotional Classrooms, interactive learning hubs, and dedicated suites for physical and occupational therapy, fostering a holistic atmosphere that prioritizes both cognitive growth and emotional well-being. \n\nThe heart of the school features a multisensory recreational zone meticulously designed to stimulate students through a curated selection of textures, scents, and acoustic landscapes. To ensure long-term sustainability, the design incorporates passive climate adaptation strategies and integrated native vegetation, which regulate the microclimate while providing a biophilic connection to nature. From the streamlined administrative wing to the tech-forward interactive classrooms, every element is synchronized under a unified conceptual palette to create a supportive, future-ready sanctuary for the entire educational community.",
    architect: "Jonnathan Brenes & Mariam Moya",
    client: "School Board",
    elevationsSectionsDesc: "Vertical views highlight the project’s commitment to climate adaptation, featuring optimized ventilation and solar protection. These sections also detail the ergonomic considerations for the therapy areas and the integration of lush vegetation within the building’s structural envelope.",
    floorPlansDesc: "The spatial organization clearly separates the administrative core from the specialized educational wings, including physical therapy and interactive labs. The circulation is designed as an intuitive \"user flow,\" ensuring easy access to recreational areas and climate-adapted transition spaces.",
    isometricViewsDesc: "Three-dimensional projections provide a clear hierarchy of the school’s complex program, from sensory-rich recreational zones to specialized therapy suites. These views highlight the seamless accessibility flow and the biophilic integration that ensures a responsive, inclusive learning environment.",
    visualizationsDesc: "These renders illustrate the integration of UX/UI principles into the physical realm, highlighting how light and color define \"Emotional Classrooms.\" The visualizations showcase the seamless transition between interactive indoor spaces and the sensory-rich outdoor environments.",
    projectGalleryDesc: "A comprehensive visual journey through the school’s diverse ecosystem, from the high-tech interactive classrooms to the therapeutic gardens. This gallery captures the essence of an inclusive design that balances rigorous accessibility standards with a vibrant, multisensory aesthetic.",
    elevationsSections: [
      "/images/project/project-escuela-dr-saenz/elevations-sections/sec2.webp",
      "/images/project/project-escuela-dr-saenz/elevations-sections/sec8.webp",
      "/images/project/project-escuela-dr-saenz/elevations-sections/sec9.webp",
    ],
    floorPlans: [
      "/images/project/project-escuela-dr-saenz/floor-plans/fplan1.webp",
      "/images/project/project-escuela-dr-saenz/floor-plans/fplan2.webp",
      "/images/project/project-escuela-dr-saenz/floor-plans/fplan3.webp",
    ],
    isometricViews: [
      "/images/project/project-escuela-dr-saenz/isometric-views/iso2.webp",
      "/images/project/project-escuela-dr-saenz/isometric-views/iso3.webp",
      "/images/project/project-escuela-dr-saenz/isometric-views/iso5.webp",
    ],
    visualizations: [
      "/images/project/project-escuela-dr-saenz/architectural-visualizations/scene1.webp",
      "/images/project/project-escuela-dr-saenz/architectural-visualizations/scene9.webp",
      "/images/project/project-escuela-dr-saenz/architectural-visualizations/scene19.webp",
    ],
    galleryComponent: ProjectMasonryGalleryComponent2,
  },
  {
    id: "3",
    title: "Habitad Sinergia Tower",
    subtitle: "Residential and Commercial Design",
    slug: "project-torre-habitadsinergia",
    pimg: "/images/project/project-torre-habitadsinergia/pimg.jpeg",
    phero: "/images/project/hero-project-2/img-4.jpg",
    sing: "/images/project/project-torre-habitadsinergia/sing.jpeg",
    num: "04",
    date: "December 2024",
    location: "San José, Costa Rica",
    dis: "",
    architect: "Jonnathan Brenes",
    client: "",
    description: "Habitat Sinergia Tower is a vertical landmark designed to redefine collective living through the lens of architectural synergy. The project focuses on the intersection of private comfort and social dynamism, creating a \"living ecosystem\" where individual units integrate seamlessly with expansive shared amenities. By prioritizing modular flexibility and sustainable urban density, the tower acts as a catalyst for community interaction, offering a balanced lifestyle that merges high-end residential design with functional, green-infused common spaces. The structure's silhouette is a testament to modern efficiency, utilizing a cohesive material palette that harmonizes with the city skyline while providing a sanctuary of light and air for its inhabitants. \n\nThe design incorporates a variety of unit typologies, each optimized for natural light and cross-ventilation, while the shared amenities—ranging from rooftop gardens to co-working spaces—are strategically placed to foster social engagement without compromising privacy. The tower's facade is a dynamic interplay of glass and greenery, creating a biophilic connection that enhances the urban experience. Through its innovative approach to vertical living, Habitat Sinergia Tower sets a new standard for residential architecture, demonstrating how thoughtful design can cultivate community and elevate the quality of life in dense urban environments.",
    elevationsSectionsDesc: "The vertical technical drawings reveal the structural soul of the tower, showcasing the rhythmic balconies and the integration of sustainable building systems. These sections detail the impressive double-height lobby and the strategic placement of communal terraces that allow the building to \"breathe\" at multiple levels.",
    floorPlansDesc: "The spatial distribution is optimized for maximum efficiency, offering versatile layouts that adapt to diverse contemporary lifestyles. The plans clearly illustrate the \"synergy\" between private quarters and fluid social zones, ensuring that every square meter contributes to the residents' well-being and ease of movement.",
    isometricViewsDesc: "These 3D cutaways provide a unique perspective on the tower’s internal logic, displaying the complex stacking of residential modules and shared amenities. The isometric projections serve to simplify the architectural density, making the sophisticated connectivity and structural harmony of the project easily digestible.",
    visualizationsDesc: "These high-impact renderings explore the tower’s presence within the urban fabric, highlighting the play of shadows across its rhythmic facade. The visualizations focus on the atmospheric quality of the common areas and the panoramic views, providing a realistic glimpse into the elevated lifestyle of the Sinergia community.",
    projectGalleryDesc: "A curated visual narrative that follows the design journey from its bold structural exterior to the intimate details of its interior finishes. This gallery captures the essence of Habitat Sinergia, showcasing a building that is not just a place to reside, but a cohesive environment designed for human connection.",
    elevationsSections: [
      "/images/project/project-torre-habitadsinergia/elevations-sections/sec5.webp",
      "/images/project/project-torre-habitadsinergia/elevations-sections/sec2.webp",
      "/images/project/project-torre-habitadsinergia/elevations-sections/sec3.webp",
    ],
    floorPlans: [
      "/images/project/project-torre-habitadsinergia/floor-plans/fplan4.webp",
      "/images/project/project-torre-habitadsinergia/floor-plans/fplan5.webp",
      "/images/project/project-torre-habitadsinergia/floor-plans/fplan3.webp",
    ],
    isometricViews: [
      "/images/project/project-torre-habitadsinergia/isometric-views/iso4.webp",
      "/images/project/project-torre-habitadsinergia/isometric-views/iso2.webp",
      "/images/project/project-torre-habitadsinergia/isometric-views/iso9.webp",
    ],
    visualizations: [
      "/images/project/project-torre-habitadsinergia/architectural-visualizations/scene14.webp",
      "/images/project/project-torre-habitadsinergia/architectural-visualizations/scene9.webp",
      "/images/project/project-torre-habitadsinergia/architectural-visualizations/scene18.webp",
    ],
    galleryComponent: ProjectMasonryGalleryComponent3,
  },
  {
    id: "4",
    title: "Arte y Moda Gallery",
    subtitle: "Cultural and Commercial Design",
    slug: "project-galeria-arteymoda",
    pimg: "/images/project/project-galeria-arteymoda/pimg.jpeg",
    phero: "/images/project/hero-project-2/img-4.jpg",
    sing: "/images/project/project-galeria-arteymoda/sing.jpeg",
    num: "04",
    date: "April 2024",
    location: "San José, Costa Rica",
    dis: "",
    architect: "Jonnathan Brenes",
    client: "",
    description: "The Arte & Moda Gallery is a conceptual sanctuary designed to blur the boundaries between wearable art and static exhibition. The architecture acts as a fluid monolithic volume, where curated lighting and open-plan geometries allow the dialogue between textile textures and artistic media to take center stage. By utilizing a minimalist industrial aesthetic, the space prioritizes versatility, enabling rapid transformations for seasonal runway shows, private viewings, or large-scale installations. The project emphasizes a \"curated journey,\" where visitors move through a series of interconnected voids that celebrate the intersection of human expression, craftsmanship, and contemporary style.",
    elevationsSectionsDesc: "Detailed vertical sections reveal the gallery’s impressive ceiling heights and the integration of specialized hanging systems for both canvases and couture. These drawings illustrate the hidden technical infrastructure—such as recessed lighting tracks and climate control—that maintains the integrity of the delicate pieces on display.",
    floorPlansDesc: "The layout is designed with a white box philosophy, featuring a flexible core that can be reconfigured for different curatorial needs. The plans detail a strategic flow that guides visitors through the main exhibition halls to private fitting suites and administrative areas, ensuring a seamless operational experience for artists and designers.",
    isometricViewsDesc: "The 3D cutaways offer a holistic view of the gallery’s spatial logic, demonstrating how the expansive open areas connect to the more intimate mezzanine levels. These isometric projections clarify the structural minimalism and the intentional use of negative space to enhance the visual impact of the exhibits.",
    visualizationsDesc: "These high-end renderings capture the sophisticated atmosphere of the gallery, emphasizing the dramatic interplay between spotlighting and material finishes. The visualizations highlight the project's ability to serve as a high-fashion backdrop while maintaining the solemnity required for a world-class art exhibition space.",
    projectGalleryDesc: "A comprehensive visual narrative that showcases the gallery in various states of use, from minimalist art showcases to high-energy fashion activations. This collection of images captures the project’s dual identity, highlighting the exquisite details, raw materials, and the transformative power of the space’s architectural lighting.",
    elevationsSections: [
      "/images/project/project-galeria-arteymoda/elevations-sections/sec1.webp",
      "/images/project/project-galeria-arteymoda/elevations-sections/sec3.webp",
      "/images/project/project-galeria-arteymoda/elevations-sections/sec4.webp",
    ],
    floorPlans: [
      "/images/project/project-galeria-arteymoda/floor-plans/fplan1.webp",
      "/images/project/project-galeria-arteymoda/floor-plans/fplan4.webp",
      "/images/project/project-galeria-arteymoda/floor-plans/fplan6.webp",
    ],
    isometricViews: [
      "/images/project/project-galeria-arteymoda/isometric-views/iso1.webp",
      "/images/project/project-galeria-arteymoda/isometric-views/iso4.webp",
      "/images/project/project-galeria-arteymoda/isometric-views/iso5.webp",
    ],
    visualizations: [
      "/images/project/project-galeria-arteymoda/architectural-visualizations/scene1.webp",
      "/images/project/project-galeria-arteymoda/architectural-visualizations/scene6.webp",
      "/images/project/project-galeria-arteymoda/architectural-visualizations/scene10.webp",
    ],
    galleryComponent: ProjectMasonryGalleryComponent4,
  },
  {
    id: "5",
    title: "JC House",
    subtitle: "Residential Design",
    slug: "project-jc-house",
    pimg: "/images/project/project-casa-taller/architectural-visualizations/sceneSlug1.webp",
    phero:
      "/images/project/project-casa-taller/architectural-visualizations/sceneSlug1.webp",
    sing: "/images/project/project-casa-taller/sing.webp",
    num: "04",
    date: "September 2024",
    location: "San José, Costa Rica",
    dis: "",
    architect: "Jonnathan Brenes",
    client: "",
    description: "JC House is a contemporary \"live-work\" residence designed to harmonize professional creativity with domestic tranquility. The architectural program is divided into two strategic levels: a dynamic ground floor that houses a dedicated workshop and open social areas, and a private upper floor focused on rest and family life. The design utilizes a robust structural grid, allowing for expansive glass facades that invite natural light into the double-height spaces. By integrating industrial materials with warm finishes, JC House stands as a functional sanctuary where the boundaries between professional craft and personal life are defined by elegant spatial transitions and a deep connection to its urban context. \n\nThe ground floor is conceived as a flexible environment that can accommodate both the demands of a busy workshop and the need for social interaction, featuring an open-plan layout that encourages fluid movement. The upper level offers a serene retreat, with carefully curated views and private outdoor terraces that provide a respite from the urban energy below. The project emphasizes sustainability through passive design strategies, including cross-ventilation and strategic shading, ensuring comfort while minimizing environmental impact. JC House exemplifies how thoughtful architectural design can create a cohesive living experience that supports both professional aspirations and personal well-being.",
    elevationsSectionsDesc: "Technical drawings illustrate the vertical complexity of the project, highlighting the double-height ceilings and the rhythmic placement of the window frames. These sections demonstrate how the house manages natural ventilation and solar control, ensuring a comfortable microclimate for both the creative studio and the living quarters.",
    floorPlansDesc: "The blueprints reveal a highly efficient layout that prioritizes fluid circulation. The ground floor is organized to accommodate a professional workshop and integrated social spaces that open toward the backyard, while the second level features a private wing with specialized suites, all connected by a central mezzanine that overlooks the heart of the home.",
    isometricViewsDesc: "",
    visualizationsDesc: "These high-fidelity renderings highlight the volumetric play of the JC House, showcasing the contrast between the solid workshop base and the lighter, more transparent residential upper level. The visualizations emphasize the evening atmosphere, where the interior lighting transforms the house into a glowing architectural beacon.",
    projectGalleryDesc: "A comprehensive visual journey through JC House, documenting the transition from the bold street-facing facade to the intimate interior details. This gallery captures the essence of the project’s materiality, featuring the synergy between exposed structural elements, sleek glass surfaces, and the vibrant greenery that frames the site.",
    elevationsSections: [
      "/images/project/project-casa-taller/elevations-sections/sec1.webp",
      "/images/project/project-casa-taller/elevations-sections/sec2.webp",
      "/images/project/project-casa-taller/elevations-sections/sec3.webp",
    ],
    floorPlans: [
      "/images/project/project-casa-taller/floor-plans/fplan1.webp",
      "/images/project/project-casa-taller/floor-plans/fplan2.webp",
      "/images/project/project-casa-taller/floor-plans/fplan3.webp",
    ],
    visualizations: [
      "/images/project/project-casa-taller/architectural-visualizations/sceneSlug2.webp",
      "/images/project/project-casa-taller/architectural-visualizations/sceneSlug3.webp",
      "/images/project/project-casa-taller/architectural-visualizations/sceneSlug4.webp",
    ],
    galleryComponent: ProjectMasonryGalleryComponent4,
  },
];
export default Projects;
